services:
  web:
    build: .  # Saját Dockerfile alapján épül
    container_name: apache_php
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"   # Apache port
      - "8091:8091" # Ratchet port
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
    networks:
      - mynetwork


  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - mynetwork

volumes:
  db_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
